TZ_7 with basic tests
romakrnv/java-kanban pull request #2
Opened 2024-04-11 14:08 UTC by romakrnv

2024-04-12 13:41 UTC, romakrnv commented
Краткое саммари по изменениям:
1) Убрал лишние реализации toString() в наследниках, и переделал его под условия ТЗ
2) Реализовал CSVTaskFormatter и FileBackedTaskManager
3) Сделал id не статическим, так как афектил тесты разных реализаций менеджера
4) Методы которые возвращают список тасок теперь возвращают List, а не Collection 
5) Изменил логику присваивания id, если таска поступает уже с id, то так его и добавляем
6) Изменил название методов createTask -> addTask (думаю более логично)

2024-04-12 14:47 UTC, kalitva requested changes

2024-04-12 14:47 UTC, kalitva commented on src/com/kanban/service/CSVTaskFormatter.java
> +public class CSVTaskFormatter {
`CSVTaskFormatter --> CsvTaskFormatter`

https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

2024-04-12 14:47 UTC, kalitva commented on src/com/kanban/service/CSVTaskFormatter.java
> +    public static String createDataToSave(List<Task> tasks, List<Epic> epics, List<Subtask> subtasks, List<Task> history) {
1. `createDataToSave --> format`
2. Многовато параметров, лучше соединить все задачи в один список и передавать в этот метод  только его (как раз будет один цикл вместо трех)

https://www.baeldung.com/java-combine-multiple-collections#2-using-the-flatmap-method

2024-04-12 14:47 UTC, kalitva commented on src/com/kanban/service/CSVTaskFormatter.java
> +                return null;
Лучше выброси отсюда исключение

2024-04-12 14:47 UTC, kalitva commented on src/com/kanban/service/CSVTaskFormatter.java
> +        } catch (NumberFormatException e) {
`NumberFormatException` не следует перехватывать, лучше заранее чекнуть строку не предмет правильного формата

2024-04-12 14:47 UTC, kalitva commented on src/com/kanban/service/CSVTaskFormatter.java
> +            System.out.println(e.getMessage());
Забудь про использование `System.out.println` (если не для дебага)

2024-04-12 14:47 UTC, kalitva commented on src/com/kanban/service/FileBackedTaskManager.java
> +import static com.kanban.service.CSVTaskFormatter.*;
Не рекомендую использовать статические импорты

2024-04-12 14:47 UTC, kalitva commented on src/com/kanban/service/FileBackedTaskManager.java
> +            System.out.println(e.getMessage());
Здесь нужно выбросить свое unchecked исключение

https://www.baeldung.com/java-checked-unchecked-exceptions

2024-04-12 14:47 UTC, kalitva commented on src/com/kanban/service/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File file) {
Возвращай по типу интерфейса

2024-04-12 14:47 UTC, kalitva commented on src/com/kanban/service/InMemoryTaskManager.java
> +    public final HistoryManager historyManager;
Это чего?  `protected`

2024-04-22 11:40 UTC, romakrnv commented on src/com/kanban/service/CSVTaskFormatter.java
> +public class CSVTaskFormatter {
done

2024-04-22 11:42 UTC, romakrnv commented on src/com/kanban/service/InMemoryTaskManager.java
> +    public final HistoryManager historyManager;
done

2024-04-22 11:43 UTC, romakrnv commented on src/com/kanban/service/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File file) {
Done

2024-04-22 11:45 UTC, romakrnv commented on src/com/kanban/service/FileBackedTaskManager.java
> +import static com.kanban.service.CSVTaskFormatter.*;
Done

2024-04-22 12:17 UTC, romakrnv commented on src/com/kanban/service/CSVTaskFormatter.java
> +            System.out.println(e.getMessage());
Done

2024-04-22 12:18 UTC, romakrnv commented on src/com/kanban/service/CSVTaskFormatter.java
> +        } catch (NumberFormatException e) {
Заменил на проверку регуляркой ```regex = "^\\d+(,\\d+)*,$";```
ты ведь это имел ввиду?

2024-04-22 12:23 UTC, romakrnv commented on src/com/kanban/service/CSVTaskFormatter.java
> +                return null;
Done

2024-04-22 20:13 UTC, romakrnv commented on src/com/kanban/service/FileBackedTaskManager.java
> +            System.out.println(e.getMessage());
Done

2024-04-22 20:48 UTC, romakrnv commented on src/com/kanban/service/CSVTaskFormatter.java
> +    public static String createDataToSave(List<Task> tasks, List<Epic> epics, List<Subtask> subtasks, List<Task> history) {
Тут что то не могу придумать как лучше сделать, если передавать список с тасками, то потом нужно будет понять какой это был объект, к примеру у сабтаске у меня изменённый toString() который добавляет ещё id эпика. А передать лист листов тоже не выходит так как у меня Task не абстрактный насколько понимаю

буду благодарен за наставление, спасибо)

2024-04-23 14:34 UTC, kalitva commented on src/com/kanban/service/CSVTaskFormatter.java
> +    public static String createDataToSave(List<Task> tasks, List<Epic> epics, List<Subtask> subtasks, List<Task> history) {
У нас же полиморфизм, так что всегда вызовется нужный `toString` в зависимости от типа задач достаточно перебрать все таски одним циклом

```java
        for (Task task : tasks) {
            dataToSave.append(task.toString()).append("\n");
        }
```

Повтори полиморфизм

Таким образом в методе останутся два параметра - задачи и история

2024-04-23 14:36 UTC, kalitva commented on src/com/kanban/service/CSVTaskFormatter.java
> +        } catch (NumberFormatException e) {
Да, только регулярку давай сделаем попроще, она не должна допускать флоат, иначе будет ошибка

2024-04-23 14:38 UTC, kalitva commented
Вместо done лучше помечай комменты, как выполненные (ставь галочку "Resolve conversation")

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#resolving-conversations

2024-04-23 14:42 UTC, kalitva approved these changes

2024-04-23 14:42 UTC, kalitva commented on src/com/kanban/service/FileBackedTaskManager.java
> +            throw new ManagerSaveException("File loading error\n");
Перевод строки не нужен

2024-04-23 14:42 UTC, kalitva commented on src/com/kanban/service/FileBackedTaskManager.java
> +    public static TaskManager loadFromFile(File file) throws ManagerSaveException {
Методы не должны деклалировать throws, для этого выбрасываемое исключение должно быть unchecked

https://www.baeldung.com/java-checked-unchecked-exceptions

2024-04-23 14:42 UTC, kalitva commented on src/com/kanban/service/ManagerSaveException.java
> +public class ManagerSaveException extends IOException {
```java
public class ManagerSaveException extends RuntimeException {
```

2024-04-23 19:19 UTC, romakrnv commented on src/com/kanban/service/CSVTaskFormatter.java
> +    public static String createDataToSave(List<Task> tasks, List<Epic> epics, List<Subtask> subtasks, List<Task> history) {
Что то не очевидно для меня было, спасибо, что подсветил, повторю

2024-04-23 19:29 UTC, romakrnv commented on src/com/kanban/service/FileBackedTaskManager.java
> +            throw new ManagerSaveException("File loading error\n");
Возможно не до конца понял какую ты строку имеешь ввиду, если написать в формате 
```java catch (IOException e) { throw new ManagerSaveException("File loading error\n"); }```
то сама идея форматирует потом в прежний вариант

2024-04-23 19:36 UTC, merged