Sprint 9 solution http api
romakrnv/java-kanban pull request #4
Opened 2024-06-02 12:47 UTC by romakrnv

2024-06-02 12:48 UTC, romakrnv commented
Что то случилось с мокито, видимо где то поломал зависимости и теперь все связанные тесты падают, пока просто закоментил InMemoryTaskManagerTest

2024-06-02 19:44 UTC, z8q requested changes

2024-06-02 19:44 UTC, z8q commented on src/com/kanban/server/HttpTaskServer.java
> +    class TasksHandler extends BaseHttpHandler implements HttpHandler {
Хэндлеры лучше выделить в отдельные классы, можно еще создать отдельный пакет handler, в него перенести

2024-06-02 19:44 UTC, z8q commented on src/com/kanban/server/HttpTaskServer.java
> +        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
Адаптеры и BaseHttpHandler тоже можно вынести в самостоятельные классы
Надо еще поставить модификаторы доступа на полях

2024-06-04 08:51 UTC, romakrnv commented
вынес в отдельные классы, решил под адаптер также добавить отдельный пакет utils 
также для тестов создал отдельные класс со статическими методами, которые часто использую для тд, так можно делать?

2024-06-04 18:28 UTC, z8q approved these changes

2024-06-05 19:55 UTC, merged